#!/usr/bin/env ruby

# Copyright (c) 2021-2022 Microchip Technology Inc. and its subsidiaries.
# SPDX-License-Identifier: MIT

require 'optparse'
require 'open3'
require 'cbor-pure'
require 'treetop'
require 'cbor-diag-parser'

LM_DBG_REG_TYPE_MIIM_C22_RD = 0
LM_DBG_REG_TYPE_MIIM_C22_WR = 1
LM_DBG_REG_TYPE_MIIM_C45_RD = 2
LM_DBG_REG_TYPE_MIIM_C45_WR = 3
LM_DBG_REG_TYPE_SWITCH_RD = 4
LM_DBG_REG_TYPE_SWITCH_WR = 5

LM_DBG_REG_FIELDS_TYPE = 0
LM_DBG_REG_FIELDS_RES_STATUS = 1
LM_DBG_REG_FIELDS_REG_ADDR = 2
LM_DBG_REG_FIELDS_REG_VALUE = 3
LM_DBG_REG_FIELDS_PORT = 4

USAGE = <<-USAGE
dbgreg - Register access debug tool


Usage:
  dbgreg [options] miim|sw [c22|c45] (<PORT>[:<MMD>]:<ADDR>[=VAL])...

Options:
  -h --help                  Show this screen.
  -d --device <URL>          IP based terminal device to connect to.
                             Ex: termhub://10.0.0.2:4000

Command details:
  Do a MIIM or Switch read or write request.
  miim: MIIM register access option.
  sw  : Switch register access option.
  c22 : Clause 22 MIIM access.
  c45 : Clause 45 MIIM access.
  PORT: 0-based switch port number.
  MMD : MMD (8 bits) for clause 45 access.
  ADDR: Register address (5/16/32 bits for c22/c45/switch access)
  VAL : Register value for write operation (16/32 bits for MIIM/switch access)
USAGE

OptionParser.new do |opts|
    opts.banner = "Usage: #{$0}"

    opts.on("-h", "--help", "") do |h|
      puts USAGE
      exit
    end

    opts.on("-d", "--device <URL>", "The device terminal URL") do |d|
      $dev = d
    end
end.parse!

$cmd = ARGV.shift

if $cmd.nil? or (not ["miim"].include?($cmd) and not ["sw"].include?($cmd))
    puts "No command specified or not supported!"
    exit -1
end


if $cmd == "miim"
  req = []
  bus = 0
  clause = :c22

  while a = ARGV.shift
    case a
    when "c22"
    when "c45"
        clause = :c45

    when /^(\w+):(\w+):(\w+)=(\w+)$/
      res = [Integer($1, exception: false),
             Integer($2, exception: false),
             Integer($3, exception: false),
             Integer($4, exception: false)]
      raise "Did not understand: #{a}" if res.include? nil
      req << { :port => res[0], :reg => ((res[1] << 16) + res[2]),
               :val => res[3], :clause => clause }

    when /^(\w+):(\w+)=(\w+)$/
      res = [Integer($1, exception: false),
             Integer($2, exception: false),
             Integer($3, exception: false)]
      raise "Did not understand: #{a}" if res.include? nil
      req << { :port => res[0], :reg => res[1],
               :val => res[2], :clause => clause }

    when /^(\w+):(\w+):(\w+)$/
      res = [Integer($1, exception: false),
             Integer($2, exception: false),
             Integer($3, exception: false)]
      raise "Did not understand: #{a}" if res.include? nil
      req << { :port => res[0], :reg => ((res[1] << 16) + res[2]),
               :clause => clause }

    when /^(\w+):(\w+)$/
      res = [Integer($1, exception: false),
             Integer($2, exception: false)]
      raise "Did not understand: #{a}" if res.include? nil
      req << { :port => res[0], :reg => res[1], :clause => clause }

    else
      puts "Did not understand: #{a}"
      exit -1
    end
  end

  req.collect! do |r|
    fields = []
    f = "#{LM_DBG_REG_FIELDS_TYPE}:"
    if r[:clause] == :c22 and r[:val].nil?
      f += LM_DBG_REG_TYPE_MIIM_C22_RD.to_s
    elsif r[:clause] == :c22 and r[:val]
      f += LM_DBG_REG_TYPE_MIIM_C22_WR.to_s
    elsif r[:clause] == :c45 and r[:val].nil?
      f += LM_DBG_REG_TYPE_MIIM_C45_RD.to_s
    elsif r[:clause] == :c45 and r[:val]
      f += LM_DBG_REG_TYPE_MIIM_C45_WR.to_s
    else
      raise "Ehhh...."
    end
    fields << f
    fields << "#{LM_DBG_REG_FIELDS_PORT}:#{r[:port]}"
    fields << "#{LM_DBG_REG_FIELDS_REG_ADDR}:#{r[:reg]}"
    fields << "#{LM_DBG_REG_FIELDS_REG_VALUE}:#{r[:val]}" if r[:val]
    "{#{fields.join(",")}}"
  end
  diag = "[#{req.join(",")}]"

  parser = CBOR_DIAGParser.new
  diag_ = parser.parse diag
  cbor = CBOR::encode(diag_.to_rb)

  dev_opts = ""
  dev_opts = "-d #{$dev}" if $dev

  cmd = "mup1ct #{dev_opts} coap post /dbg/reg --content-type 60 --accept 60"
  puts cmd
  cbor_out, err, status = Open3.capture3(cmd, stdin_data: cbor, binmode: true)
  puts "Status: #{status.to_i}, stderr: #{err.strip}, got #{cbor_out.size} bytes"

  begin
    back = CBOR::decode(cbor_out)
    #pp back
    back.each_with_index do |e, idx|
        hdr = "Oper  Port  "
        str = ""
        a = e.values
        t = a[0]
        if (t == LM_DBG_REG_TYPE_MIIM_C22_RD || t == LM_DBG_REG_TYPE_MIIM_C45_RD)
            str += "RD"
        else
            str += "WR"
        end
        str += ("    %-6u" % a[1])
        r = a[2]
        if (t == LM_DBG_REG_TYPE_MIIM_C22_RD || t == LM_DBG_REG_TYPE_MIIM_C22_WR)
            hdr += "Addr  "
            str += ("0x%02X  " % r)
        else
            hdr += "MMD   Addr    "
            str += ("0x%02X  " % (r >> 16))
            str += ("0x%04X  " % (r & 0xffff))
        end
        v = a[3]
        16.times do |i|
            str += "." if ((i > 0) && (i % 8) == 0)
            str += (((1 << (15 - i)) & v) > 0 ? "1" : "0")
        end
        str += ("  0x%04X" % v)
        str += "  #{v}"
        if (idx == 0)
            puts ""
            hdr.length.times do
                print " "
            end
            puts "Value              Value   Value"
            hdr += "15     8.7      0  Hex     Decimal"
            puts hdr
        end
        puts str
    end
  rescue
    puts "Failed to decode output as cbor"
    o, e, s = Open3.capture3("hexdump -C", stdin_data: cbor_out, binmode: true)
    puts o
  end
else
  req = []
  while a = ARGV.shift
    case a
    when /^(\w+)=(\w+)$/
      res = [Integer($1, exception: false),
             Integer($2, exception: false)]
      raise "Did not understand: #{a}" if res.include? nil
      req << { :reg => res[0], :val => res[1]}
    when /^(\w+)$/
      res = [Integer($1, exception: false)]
      raise "Did not understand: #{a}" if res.include? nil
      req << { :reg => res[0]}
    else
      puts "Did not understand: #{a}"
      exit -1
    end
  end

  req.collect! do |r|
    fields = []
    f = "#{LM_DBG_REG_FIELDS_TYPE}:"
    if r[:reg] && r[:val]
      f += LM_DBG_REG_TYPE_SWITCH_WR.to_s
    elsif r[:reg]
      f += LM_DBG_REG_TYPE_SWITCH_RD.to_s
    else
      raise "Ehhh...."
    end
    fields << f
    fields << "#{LM_DBG_REG_FIELDS_REG_ADDR}:#{r[:reg]}"
    fields << "#{LM_DBG_REG_FIELDS_REG_VALUE}:#{r[:val]}" if r[:val]
    "{#{fields.join(",")}}"
  end
  diag = "[#{req.join(",")}]"
#  pp diag
  parser = CBOR_DIAGParser.new
  diag_ = parser.parse diag
  cbor = CBOR::encode(diag_.to_rb)

  dev_opts = ""
  dev_opts = "-d #{$dev}" if $dev

  cmd = "mup1ct #{dev_opts} coap post /dbg/reg --content-type 60 --accept 60"
  puts cmd
  cbor_out, err, status = Open3.capture3(cmd, stdin_data: cbor, binmode: true)
  puts "Status: #{status.to_i}, stderr: #{err.strip}, got #{cbor_out.size} bytes"

  begin
    back = CBOR::decode(cbor_out)
    #pp back
    back.each_with_index do |e, idx|
        if (idx == 0)
            puts ""
            puts "                  Value                                Value       Value"
            puts "Oper  Address     31    24.23    16.15     8.7      0  Hex         Decimal"
        end
        a = e.values
        str = (a[0] == LM_DBG_REG_TYPE_SWITCH_RD ? "RD" : "WR")
        str += "    "
        str += ("0x%08X  " % a[1])
        v = a[2]
        32.times do |i|
            str += "." if ((i > 0) && (i % 8) == 0)
            str += (((1 << (31 - i)) & v) > 0 ? "1" : "0")
        end
        str += ("  0x%08X" % v)
        str += "  #{v}"
        puts str
    end
  rescue
    puts "Failed to decode output as cbor"
    o, e, s = Open3.capture3("hexdump -C", stdin_data: cbor_out, binmode: true)
    puts o
  end
end


