#!/usr/bin/env ruby

# Copyright (c) 2021-2022 Microchip Technology Inc. and its subsidiaries.
# SPDX-License-Identifier: MIT

# mup1ct - MUP1 CoAP/CORECONF client tool using libeasy handlers
#
# Adding a new command:
# 1. Create a command class inheriting from Command:
#
#    class MyCommand < Command
#      def parse_args(argv)
#        @arg = argv.shift  # parse command-specific arguments
#      end
#
#      def response_wait
#        context[:wait] || 1  # default timeout in seconds
#      end
#
#      def execute
#        # Command logic here. Available via context:
#        #   context[:mup1]        - MUP1 handler for low-level TX/RX
#        #   context[:dut]         - DUT handler for polling
#        #   context[:tracer]      - Tracer for debug output
#        #   context[:ping_handler]- Ping response handler
#        #   context[:input]       - Input data from -i or stdin
#        #   context[:output_file] - Output file from -o option
#        #   context[:wait]        - Wait time from -w option
#        #   context[:wait_forever]- True if -w -1
#        #   context[:content_type]- CoAP content-type option
#        #   context[:accept]      - CoAP accept option
#        #   context[:sid]         - SID from --sid option
#        #   context[:keys]        - Keys from --keys option
#        #   context[:flags]       - Flags from --flags option
#        #
#        # Helper methods from base Command class:
#        #   poll_until(timeout, forever: false) - poll with timeout
#        #   write_output(data) - write to stdout or -o file
#      end
#    end
#
# 2. Register in CommandFactory::COMMANDS:
#
#    COMMANDS = {
#      ...
#      "mycommand" => MyCommand,
#    }
#

require 'optparse'
require 'uri'
require 'base64'
require 'shellwords'
require "nokogiri"
require_relative "../libeasy/handler.rb"
require_relative '../libeasy/frame/coap.rb'
require_relative '../libeasy/cbor-diag.rb'

EXAMPLES = <<~EXAMPLES

  Examples:
    mup1ct -d termhub://10.0.0.2:4000 ping
    mup1ct cc get --sid 7026 | cbor-diag  # Deprecated, mup1cc tool instead
    mup1ct cc get --sid 5010 --keys s:1 --flags c=n # Deprecated, mup1cc tool instead
    mup1ct cc fetch --ds c --content-type 141 --accept 142 < payload.cbor # Deprecated, mup1cc tool instead
    mup1ct coap get .well-known/core
    mup1ct coap put fw/image < firmware.fip
    mup1ct trace :                        # Get all trace levels
    mup1ct trace port:info                # Set port trace to info
    mup1ct dump "a:port:0::"              # Dump AIL port state for port 0
    mup1ct dump ":::"                     # Dump all layers, groups, ports
    mup1ct sysrq trace port:info          # Deprecated, use 'trace' instead
    mup1ct sysrq dump ":::"               # Deprecated, use 'dump' instead
EXAMPLES

# Use libeasy constants
Coap = Et::Frame::Coap

COAP_ACK_WAIT_TIME = 1       # Wait for ACK in one second then retransmit
COAP_LAST_ACK_WAIT_TIME = 5  # Wait for the last ACK

# SID to base64url encoding for CORECONF URIs
def sid_encode(sid)
  base64_urlsafe = ('A'..'Z').to_a + ('a'..'z').to_a + ('0'..'9').to_a + ['-', '_']
  buf = ""
  save = false
  60.step(0, -6) do |i|
    n = (sid.to_i >> i) & 0x3f
    save = true if n != 0
    buf += base64_urlsafe[n] if save
  end
  buf
end

# Tracer class to control debug output (send to STDERR, not STDOUT)
class Tracer
  def initialize(level = :silent)
    @level = level
  end

  def t(mod, level, msg)
    return if @level == :silent

    case level
    when :fatal
      STDERR.puts "FATAL: #{mod}: #{msg}" if [:fatal, :error, :info, :debug].include?(@level)
    when :err
      STDERR.puts "#{mod} #{msg}" if [:error, :info, :debug].include?(@level)
    when :info
      # Suppress info level by default
    when :debug
      STDERR.puts "DEBUG: #{mod}: #{msg}" if [:debug].include?(@level)
    end
  end
end

# Console handler - receives MUP1 non-protocol data and announces
class Mup1Con < Et::Handler::Base
  def initialize lower_layer
    super "CON"
    lower_layer.handler_reg Et::Handler::Mup1::MUP1_CB_NON_MUP1, self
    lower_layer.handler_reg Et::Handler::Mup1::MUP1_CB_ANNOUNCE, self
  end

  def rx type, data
    case type
    when Et::Handler::Mup1::MUP1_CB_NON_MUP1
      data.strip!
      puts "CON: #{data.inspect}" if data.size > 0
    when Et::Handler::Mup1::MUP1_CB_ANNOUNCE
      puts "ANNOUNCE: #{data.inspect}"
    end
  end
end

# Ping handler - receives ping responses
class PingHandler < Et::Handler::Base
  attr_reader :pong_received, :pong_data

  def initialize lower_layer
    super "PING"
    @pong_received = false
    @pong_data = nil
    lower_layer.handler_reg Et::Handler::Mup1::MUP1_CB_PING, self
  end

  def rx type, data
    @pong_received = true
    @pong_data = data
  end
end

# Trace handler for -t/-T options
class TraceHandler < Et::Handler::Base
  attr_accessor :trace_enabled

  def initialize lower_layer
    super "TRACE"
    @trace_enabled = false
    lower_layer.handler_reg Et::Handler::Mup1::MUP1_CB_TRACE, self
  end

  def rx type, data
    STDERR.print data if @trace_enabled
  end
end

# CoAP client wrapper for libeasy CoAP handler
class CoapClient
  attr_reader :payload_rx, :code_class, :code_detail

  def initialize mup1_handler, tracer = nil, dtls_enable = false, pem_key = nil
    @mup1 = mup1_handler
    @tracer = tracer
    @dtls_enable = dtls_enable

    if dtls_enable
      if pem_key.nil?
        key_file_name = "client_key.pem"
        if File.exist?(key_file_name)
          pem_key = File.read(key_file_name)
        else
          pem_key = pem_ec_key_gen
          File.write(key_file_name, pem_key)
        end
      end
      config = Et::Handler::Dtls_Config.new(pem_key)
      @dtls = Create_Dtls_Handlers(config, mup1_handler, tracer)
      @coap = Et::Handler::Coap.new(@dtls, tracer)
    else
      @coap = Et::Handler::Coap.new(mup1_handler, tracer)
    end
  end

  def request(method, uri, payload = nil, opts = {})
    res = @coap.req(method, uri, payload, opts)
    @payload_rx = res.payload_rx if res
    @code_class = res.code_class if res
    @code_detail = res.code_detail if res
    return res
  end

  def get(uri, opts = {})
    request(Coap::CODE_GET, uri, nil, opts)
  end

  def put(uri, payload, opts = {})
    request(Coap::CODE_PUT, uri, payload, opts)
  end

  def del(uri, opts = {})
    request(Coap::CODE_DEL, uri, nil, opts)
  end

  def post(uri, payload, opts = {})
    request(Coap::CODE_POST, uri, payload, opts)
  end

  def fetch(uri, payload, opts = {})
    request(Coap::CODE_FETCH, uri, payload, opts)
  end

  def ipatch(uri, payload, opts = {})
    request(Coap::CODE_IPATCH, uri, payload, opts)
  end
end

# CoAP response code text lookups
SUCCESS_CODES = {1=>"Created", 2=>"Deleted", 3=>"Valid", 4=>"Changed", 5=>"Content"}
CLIENT_ERROR_CODES = {0=>"Bad Request", 1=>"Unauthorized", 2=>"Bad Option", 3=>"Forbidden",
                      4=>"Not Found", 5=>"Method Not Allowed", 6=>"Not Acceptable",
                      8=>"Request Entity Incomplete", 9=>"Conflict", 12=>"Precondition Failed",
                      13=>"Request Entity Too Large", 15=>"Unsupported Content-Format"}
SERVER_ERROR_CODES = {0=>"Internal Server Error", 1=>"Not Implemented", 2=>"Bad Gateway",
                      3=>"Service Unavailable", 4=>"Gateway Timeout", 5=>"Proxying Not Supported"}

def success_detail(d) = SUCCESS_CODES[d.to_i] || "Unknown"
def c_error_detail(d) = CLIENT_ERROR_CODES[d.to_i] || "Unknown"
def s_error_detail(d) = SERVER_ERROR_CODES[d.to_i] || "Unknown"

def print_response_code(code_class, code_detail)
  if code_class == 2
    STDERR.puts "RESPONSE-CODE: class 2 detail #{code_detail} Success #{success_detail(code_detail)}"
  elsif code_class == 4
    STDERR.puts "RESPONSE-CODE: class 4 detail #{code_detail} Client Error #{c_error_detail(code_detail)}"
  elsif code_class == 5
    STDERR.puts "RESPONSE-CODE: class 5 detail #{code_detail} Server Error #{s_error_detail(code_detail)}"
  end
end

# Base class for all commands
class Command
  attr_reader :context

  def initialize(context)
    @context = context
  end

  def parse_args(argv)
    # Override in subclasses
  end

  def execute
    raise NotImplementedError, "Subclass must implement execute"
  end

  def response_wait
    context[:wait] || 1
  end

  def poll_until(timeout_sec, forever: false)
    timeout_end = Time.now + timeout_sec
    while forever || Time.now < timeout_end
      context[:dut].timeout_abs_set(Time.now + 0.1)
      context[:dut].poll
      yield if block_given?
    end
  end

  def write_output(data)
    if context[:output_file]
      context[:output_file].write(data)
      context[:output_file].close
    else
      print data
    end
  end
end

# Ping command
class PingCommand < Command
  def response_wait
    context[:wait] || 1
  end

  def execute
    start_time = Process.clock_gettime(Process::CLOCK_MONOTONIC)
    ping_handler = context[:ping_handler]
    mup1 = context[:mup1]
    forever = context[:wait_forever]

    mup1.tx("p", "")

    timeout_end = Time.now + response_wait
    while !ping_handler.pong_received && (Time.now < timeout_end || forever)
      context[:dut].timeout_abs_set(Time.now + 0.1)
      context[:dut].poll
    end

    if ping_handler.pong_received
      elapsed = Process.clock_gettime(Process::CLOCK_MONOTONIC) - start_time
      mup1_data_elements = ping_handler.pong_data.split(' ')
      STDERR.puts "Pong received in #{(elapsed * 1000).truncate(2)} ms"
      STDERR.puts "Build #{mup1_data_elements[0]}"
      STDERR.puts "Up Time #{mup1_data_elements[1]}"
      STDERR.puts "Data size #{mup1_data_elements[2]}" if mup1_data_elements[2]
      STDERR.puts "Version #{mup1_data_elements[3]}" if mup1_data_elements[3]
    else
      STDERR.puts "No PONG frame received"
    end
  end
end

# CoAP command (coap/coaps)
class CoapCommand < Command
  attr_accessor :method, :url, :payload, :dtls_enable

  def parse_args(argv)
    @method = argv.shift
    if !["get", "put", "post", "del", "ipatch", "fetch"].include?(@method)
      puts "coap method invalid"
      exit(-1)
    end

    if argv.empty?
      puts "The coap URL is missing"
      exit(-1)
    end
    @url = argv.shift

    @payload = read_payload(argv)
  end

  def response_wait
    context[:wait] || 3 * COAP_ACK_WAIT_TIME
  end

  def execute
    opts = {}
    opts[:content_type] = context[:content_type] if context[:content_type]
    opts[:accept] = context[:accept] if context[:accept]

    pem_key = context[:pem_key] ? File.read(context[:pem_key]) : nil
    coap_client = CoapClient.new(context[:mup1], context[:tracer], @dtls_enable, pem_key)

    case @method
    when "get"
      res = coap_client.get(@url, opts)
    when "put"
      res = coap_client.put(@url, @payload, opts)
    when "del"
      res = coap_client.del(@url, opts)
    when "post"
      res = coap_client.post(@url, @payload, opts)
    when "ipatch"
      res = coap_client.ipatch(@url, @payload, opts)
    when "fetch"
      res = coap_client.fetch(@url, @payload, opts)
    end

    handle_response(res)
  end

  private

  def read_payload(argv)
    if context[:input]
      context[:input]
    elsif !STDIN.tty?
      STDIN.read
    elsif !argv.empty?
      argv.shift
    end
  end

  def handle_response(res)
    if res
      print_response_code(res.code_class, res.code_detail)
      if res.payload_rx && !res.payload_rx.empty?
        write_output(res.payload_rx)
      end
    else
      STDERR.puts "No COAP response frame received"
    end
  end
end

# CC (CORECONF) command
class CcCommand < Command
  attr_accessor :method, :payload
  attr_accessor :datastore, :sid, :keys, :flags

  def initialize(context)
    super
    @datastore = "c"
    @keys = []
    @flags = []
  end

  def parse_args(argv)
    @method = argv.shift
    if !["get", "put", "post", "del", "fetch", "ipatch"].include?(@method)
      puts "cc method invalid"
      exit(-1)
    end

    parse_sid
    parse_keys
    parse_flags
    @payload = read_payload(argv)
  end

  def response_wait
    context[:wait] || 3 * COAP_ACK_WAIT_TIME
  end

  def execute
    uri = build_uri
    opts = {}
    opts[:content_type] = context[:content_type] if context[:content_type]
    opts[:accept] = context[:accept] if context[:accept]

    coap_client = CoapClient.new(context[:mup1], context[:tracer], false, nil)

    case @method
    when "get"
      res = coap_client.get(uri, opts)
    when "put"
      res = coap_client.put(uri, @payload, opts)
    when "del"
      res = coap_client.del(uri, opts)
    when "post"
      res = coap_client.post(uri, @payload, opts)
    when "fetch"
      res = coap_client.fetch(uri, @payload, opts)
    when "ipatch"
      res = coap_client.ipatch(uri, @payload, opts)
    end

    handle_response(res)
  end

  private

  def parse_sid
    return if context[:sid].nil?

    if !["get", "put", "post", "del"].include?(@method)
      puts("Option --sid is not valid in #{@method} command.")
      exit(-1)
    end

    s = context[:sid]
    if (s =~ /\b\d/) != nil
      $stderr.puts "MUP1CT SID num #{s}"
      @sid = s
    elsif (s =~ /\b[a-zA-Z\/][a-zA-Z\/:-]*/) != nil
      $stderr.puts "MUP1CT SID name #{s}"
      doc = File.open("../docs/sids.xml") { |f| Nokogiri::XML(f) }
      n = doc.xpath("/yang-objs/obj[@full_path=\"#{s}\"]/@sid").first
      if n != nil
        @sid = n.value
      else
        puts("SID not found.")
        exit(-1)
      end
    else
      puts "invalid SID"
      exit(-1)
    end
    $stderr.puts "MUP1CT SID #{@sid} -> #{sid_encode(@sid)}"
  end

  def parse_keys
    return if context[:keys].nil? || context[:keys].empty?

    if !["get", "put", "post", "del"].include?(@method)
      puts("Option --keys is not valid in #{@method} command.")
      exit(-1)
    end

    @keys_diag = []
    context[:keys].each do |key|
      key.strip!
      case key
      when /^(s):(.+)/
        @keys_diag << "\"#{Shellwords.escape(%Q[#{$2}])}\""
      when /^(i):([+-]?[0-9]+)/
        @keys_diag << $2.to_i
      when /^(b):(true|false)/
        @keys_diag << $2
      else
        puts "Wrong instance identifier key #{key}"
        exit(-1)
      end
    end
  end

  def parse_flags
    return if context[:flags].nil? || context[:flags].empty?

    if !["get", "fetch"].include?(@method)
      puts("Option --flags not valid in #{@method} command.")
      exit(-1)
    end

    @flags_diag = []
    c_exist = false
    d_exist = false

    context[:flags].each do |flag|
      $stderr.puts "MUP1CT flags #{flag}"
      case flag
      when /c=[c,n,a]/
        if c_exist
          puts "double c query"
          exit(-1)
        end
        c_exist = true
        @flags_diag << flag
      when /d=[a,t]/
        if d_exist
          puts "double d query"
          exit(-1)
        end
        d_exist = true
        @flags_diag << flag
      else
        puts "Wrong c and/or d query"
        exit(-1)
      end
    end
  end

  def read_payload(argv)
    if context[:input]
      context[:input]
    elsif !STDIN.tty?
      STDIN.read
    elsif !argv.empty?
      argv.shift
    end
  end

  def build_uri
    @keys_diag ||= []
    @flags_diag ||= []

    uri_paths = [@datastore]
    uri_paths << sid_encode(@sid) if @sid

    cbor_seq = @keys_diag.map { |k| diag2cbor(k.to_s) }.join
    uri_keys = [Base64.urlsafe_encode64(cbor_seq, padding: false)]
    uri_keys.concat(@flags_diag)

    $stderr.puts "MUP1CT method #{@method}"
    $stderr.puts "MUP1CT paths  #{uri_paths}"
    $stderr.puts "MUP1CT coap_url_keys: #{@keys_diag} -> #{uri_keys}"

    uri = "/" + uri_paths.join("/")
    uri += "?" + uri_keys.reject(&:empty?).join("&") if uri_keys.any? { |k| !k.empty? }
    uri
  end

  def handle_response(res)
    if res
      print_response_code(res.code_class, res.code_detail)
      if res.payload_rx && !res.payload_rx.empty?
        write_output(res.payload_rx)
      end
    else
      STDERR.puts "No COAP response frame received"
    end
  end
end

# Dump command - CoAP POST to /dbg/dump
# Firmware expects format "layer:group:ports:flags" (at least 3 colons).
# Pad with trailing colons so users can use short forms like "a:vlan:"
class DumpCommand < Command
  def parse_args(argv)
    arg = argv.empty? ? "" : argv.shift
    colons = arg.count(":")
    arg += ":" * (3 - colons) if colons < 3
    @args = arg
  end

  def response_wait
    context[:wait] || 3 * COAP_ACK_WAIT_TIME
  end

  def execute
    coap_client = CoapClient.new(context[:mup1], context[:tracer], false, nil)
    res = coap_client.post("dbg/dump", @args)

    if res
      print_response_code(res.code_class, res.code_detail)
      write_output(res.payload_rx) if res.payload_rx && !res.payload_rx.empty?
    else
      STDERR.puts "No COAP response frame received"
    end
  end
end

# Trace command - CoAP POST to /dbg/trace
class TraceCommand < Command
  def parse_args(argv)
    @args = argv.empty? ? ":" : argv.shift
  end

  def response_wait
    context[:wait] || 3 * COAP_ACK_WAIT_TIME
  end

  def execute
    coap_client = CoapClient.new(context[:mup1], context[:tracer], false, nil)
    res = coap_client.post("dbg/trace", @args)

    if res
      print_response_code(res.code_class, res.code_detail)
      write_output(res.payload_rx) if res.payload_rx && !res.payload_rx.empty?
    else
      STDERR.puts "No COAP response frame received"
    end
  end
end

# Sysrq command (deprecated) - wraps dump/trace via CoAP
class SysrqCommand < Command
  def parse_args(argv)
    @subcommand = argv.shift
    case @subcommand
    when "trace", "dump"
      STDERR.puts "WARNING: 'sysrq' is deprecated, use '#{@subcommand}' instead"
      @inner = CommandFactory.create(@subcommand, context)
      @inner.parse_args(argv)
    else
      puts "sysrq subcommand invalid"
      exit(-1)
    end
  end

  def response_wait
    @inner.response_wait
  end

  def execute
    @inner.execute
  end
end

# Listen command
class ListenCommand < Command
  def response_wait
    -1  # Forever by default
  end

  def execute
    forever = context[:wait_forever] || (context[:wait].nil? || context[:wait] < 0)
    wait_time = context[:wait] ? context[:wait].abs : 1

    poll_until(wait_time, forever: forever)
  end
end

# Command factory
class CommandFactory
  COMMANDS = {
    "ping" => PingCommand,
    "coap" => CoapCommand,
    "coaps" => CoapCommand,
    "cc" => CcCommand,
    "dump" => DumpCommand,
    "trace" => TraceCommand,
    "sysrq" => SysrqCommand,
    "listen" => ListenCommand
  }

  def self.create(name, context)
    klass = COMMANDS[name]
    return nil unless klass

    cmd = klass.new(context)
    cmd.dtls_enable = (name == "coaps") if cmd.respond_to?(:dtls_enable=)
    cmd
  end

  def self.valid?(name)
    COMMANDS.key?(name)
  end

  def self.names
    COMMANDS.keys
  end
end

# Main application class
class Mup1ctApp
  def initialize
    @opt = {}
    @cc_opt = { :keys => [], :flags => [], :datastore => "c" }
    @opt[:checksum_type] = :internet
    @opt[:baudrate] = 115200
  end

  def run(argv)
    parse_options(argv)
    validate_options

    cmd_name = argv.shift
    if cmd_name.nil? || !CommandFactory.valid?(cmd_name)
      puts "command is invalid" if cmd_name
      puts "No command specified!" if cmd_name.nil?
      puts
      puts @optparser
      exit(-1)
    end

    setup_io
    context = setup_handlers(cmd_name)

    command = CommandFactory.create(cmd_name, context)
    command.datastore = @cc_opt[:datastore] if command.respond_to?(:datastore=)
    command.parse_args(argv)

    command.execute

    handle_trace_timeout(context)
  end

  private

  def parse_options(argv)
    @optparser = OptionParser.new do |opts|
      opts.banner = <<~BANNER
        mup1ct - MUP1 CoAP/CORECONF client tool

        Usage:
          mup1ct [options] ping
          mup1ct [options] coap[s] (get|put|del|post|fetch|ipatch) <URL-PATH>
          mup1ct [options] dump <LAYER>:<GROUP>:<PORTS>[:<FLAGS>[:<ACTION>]]
          mup1ct [options] trace <MODULE>:<LEVEL>
          mup1ct [options] sysrq (trace|dump) ...  (deprecated)
          mup1ct [options] listen

      BANNER

      opts.separator "General options:"
      opts.on("-d", "--device URL", "Terminal URL (e.g., termhub://10.0.0.2:4000)") { |d| @opt[:device] = d }
      opts.on("-i", "--input FILE", "Read payload from FILE instead of STDIN") { |i| @opt[:input] = i }
      opts.on("-o", "--output FILE", "Write output to FILE instead of STDOUT") { |o| @opt[:output] = o }
      opts.on("-w", "--wait SEC", Float, "Response wait time (-1 = forever)") { |w| @opt[:wait] = w }
      opts.on("-t", "--trace", "Print traces to STDERR") { |t| @opt[:trace] = t }
      opts.on("-T", "--trace-timeout SEC", Float, "Wait SEC for traces after command") { |tw| @opt[:Trace] = tw }
      opts.on("-k", "--key FILE.pem", "PEM key file for DTLS (coaps only)") { |k| @opt[:pem_key] = k }
      opts.on("--checksum-type TYPE", [:internet, :crc32], "MUP1 checksum (default: internet)") { |cs| @opt[:checksum_type] = cs }
      opts.on("--baudrate RATE", Integer, "Serial baud rate (default: 115200)") { |br| @opt[:baudrate] = br }

      opts.separator ""
      opts.separator "CoAP/CC options:"
      opts.on("--content-type NUM", Integer, "CoAP Content-Format option") { |ct| @cc_opt[:content_type] = ct }
      opts.on("--accept NUM", Integer, "CoAP Accept option") { |ct| @cc_opt[:accept] = ct }

      opts.separator ""
      opts.separator "CC command options (Deprecated, use mup1cc instead):"
      opts.separator "mup1ct [options] cc (get|put|del|post|fetch|ipatch) [--sid SID] [--ds DS]"
      opts.on("--ds DS", "Datastore (default: c)") { |ds| @cc_opt[:datastore] = ds }
      opts.on("--sid SID", "SID number to address") { |a| @cc_opt[:sid] = a }
      opts.on("--keys K1,K2,...", Array, "Instance keys (s:str, i:int, b:bool)") { |k| @cc_opt[:keys] = k }
      opts.on("--flags F1,F2,...", Array, "Query flags (c=c|n|a, d=a|t)") { |f| @cc_opt[:flags] = f }

      opts.separator EXAMPLES
      opts.on_tail("-h", "--help", "Show this help") { puts opts; exit }
    end
    @optparser.parse!(argv)
  end

  def validate_options
    if !@opt[:trace].nil? && !@opt[:Trace].nil?
      puts "Both -t and -T cannot be specified"
      exit(-1)
    end
  end

  def setup_io
    $stdin.binmode
    $stdout.binmode

    if @opt[:input]
      if !File.exist?(@opt[:input])
        puts "File does not exist"
        exit(-1)
      end
      file = File.open(@opt[:input])
      file.binmode
      @input_data = file.read
      file.close
    end

    if @opt[:output]
      @output_file = File.open(@opt[:output], "w")
    end
  end

  def setup_handlers(cmd_name)
    device = get_device
    tracer = Tracer.new(:silent)

    dut = Et::Handler::Dut.new(device, baud: @opt[:baudrate])

    # Check if libeasy Mup1 handler supports checksum_type parameter
    mup1_params = Et::Handler::Mup1.instance_method(:initialize).parameters
    has_checksum_type = mup1_params.any? { |p| p[1] == :checksum_type }

    if has_checksum_type
      mup1 = Et::Handler::Mup1.new(dut, tracer, true, @opt[:checksum_type])
    else
      if @opt[:checksum_type] != :internet
        STDERR.puts "Warning: This version of libeasy does not support CRC32 checksum"
      end
      mup1 = Et::Handler::Mup1.new(dut, tracer, true)
    end

    dtls_enable = (cmd_name == "coaps")
    if dtls_enable
      mon = Mup1Con.new(mup1)
    end

    trace_handler = TraceHandler.new(mup1)
    trace_handler.trace_enabled = @opt[:trace] || @opt[:Trace]

    ping_handler = PingHandler.new(mup1)

    # Calculate wait time
    wait = @opt[:wait]
    wait_forever = wait && wait.to_i < 0

    {
      :dut => dut,
      :mup1 => mup1,
      :tracer => tracer,
      :trace_handler => trace_handler,
      :ping_handler => ping_handler,
      :input => @input_data,
      :output_file => @output_file,
      :wait => wait ? wait.to_i.abs : nil,
      :wait_forever => wait_forever,
      :pem_key => @opt[:pem_key],
      :content_type => @cc_opt[:content_type],
      :accept => @cc_opt[:accept],
      :sid => @cc_opt[:sid],
      :keys => @cc_opt[:keys],
      :flags => @cc_opt[:flags]
    }
  end

  def get_device
    return @opt[:device] if @opt[:device]

    if File.exist?('.mscc-libeasy-topology.yaml')
      conf = YAML.load_file(".mscc-libeasy-topology.yaml")
    else
      conf = YAML.load_file("#{ENV["HOME"]}/.mscc-libeasy-topology.yaml")
    end
    conf["dut"]["terminal"]
  end

  def handle_trace_timeout(context)
    return unless @opt[:Trace]

    trace_wait = @opt[:Trace].to_i.abs
    trace_restart = @opt[:Trace].to_i < 0

    trace_end = Time.now + trace_wait
    while Time.now < trace_end
      context[:dut].poll
      trace_end = Time.now + trace_wait if trace_restart
    end
  end
end

# Main entry point
if __FILE__ == $0
  if ARGV.empty?
    puts "No command specified!"
    puts
    app = Mup1ctApp.new
    app.run(["--help"])
    exit 0
  end

  app = Mup1ctApp.new
  app.run(ARGV)
end
